# Generated by Django 4.1.6 on 2023-02-11 20:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='actormodel',
            name='dob',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='actormodel',
            name='oscar',
            field=models.BooleanField(default=False),
        ),
    ]
