# Generated by Django 4.1.6 on 2023-02-11 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_actormodel_dob_actormodel_oscar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actormodel',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
