# Generated by Django 4.1.6 on 2023-02-11 21:18

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_actormodel_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='actormovieModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.actormodel')),
            ],
        ),
        migrations.CreateModel(
            name='movieModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('release_date', models.DateField(default=django.utils.timezone.now)),
                ('imdb_rating', models.FloatField(default=0)),
                ('actors', models.ManyToManyField(through='api.actormovieModel', to='api.actormodel')),
            ],
        ),
        migrations.AddField(
            model_name='actormoviemodel',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.moviemodel'),
        ),
    ]
